INSERT INTO units (num_of_rooms, floor, accommodation_type, price_per_night, description)
VALUES (1, 1, 'FLAT', 80, 'Cozy flat near the park'),
       (2, 3, 'FLAT', 90, 'Modern flat downtown'),
       (3, 2, 'APARTMENT', 120, 'Spacious apartment with balcony'),
       (2, 5, 'FLAT', 110, 'Nice flat near the lake'),
       (1, 4, 'FLAT', 70, 'Small but comfortable flat'),
       (3, 6, 'APARTMENT', 150, 'Penthouse with city view'),
       (2, 2, 'FLAT', 95, 'Quiet flat in a residential area'),
       (1, 8, 'FLAT', 85, 'Flat with a great skyline view'),
       (4, 3, 'HOME', 200, 'Luxury home with private pool'),
       (2, 9, 'APARTMENT', 130, 'Apartment close to metro station'),
       (1, 5, 'FLAT', 75, 'Minimalist flat near university'),
       (2, 7, 'FLAT', 105, 'Bright flat with modern decor'),
       (3, 10, 'APARTMENT', 160, 'Spacious top-floor apartment'),
       (4, 1, 'HOME', 220, 'Elegant home in a quiet neighborhood'),
       (2, 6, 'FLAT', 115, 'Flat with excellent connectivity'),
       (1, 3, 'FLAT', 65, 'Budget-friendly flat for solo travelers'),
       (3, 8, 'APARTMENT', 140, 'Apartment with river view'),
       (2, 4, 'FLAT', 100, 'Modern flat with rooftop access'),
       (1, 2, 'FLAT', 78, 'Compact flat perfect for business trips'),
       (3, 5, 'APARTMENT', 155, 'Comfortable apartment with spacious living area'),
       (4, 7, 'HOME', 210, 'Home with garden and barbecue area'),
       (2, 10, 'FLAT', 120, 'Luxury flat in city center'),
       (1, 9, 'FLAT', 82, 'Artistic flat with a unique interior'),
       (3, 1, 'APARTMENT', 130, 'Modern apartment with a home office setup'),
       (4, 6, 'HOME', 230, 'Home with private terrace and hot tub'),
       (2, 3, 'FLAT', 95, 'Flat near shopping district'),
       (1, 7, 'FLAT', 77, 'Affordable flat close to nightlife'),
       (3, 9, 'APARTMENT', 145, 'Spacious apartment with 2 balconies'),
       (4, 2, 'HOME', 240, 'Exclusive home with beach access'),
       (2, 8, 'FLAT', 108, 'Well-equipped flat for families'),
       (1, 6, 'FLAT', 79, 'Compact flat with modern amenities'),
       (3, 4, 'APARTMENT', 135, 'Apartment with mountain view'),
       (4, 10, 'HOME', 250, 'High-end home with infinity pool'),
       (2, 5, 'FLAT', 110, 'Fine flat near Zoo'),
       (1, 1, 'FLAT', 68, 'Simple yet stylish flat'),
       (3, 2, 'APARTMENT', 125, 'Apartment with easy airport access'),
       (4, 3, 'HOME', 205, 'Home with spacious backyard'),
       (2, 7, 'FLAT', 115, 'Comfortable flat with modern appliances'),
       (1, 8, 'FLAT', 88, 'Flat with artistic decor'),
       (3, 6, 'APARTMENT', 150, 'Spacious apartment with gym access'),
       (4, 5, 'HOME', 215, 'Exclusive home with private chef services'),
       (2, 9, 'FLAT', 125, 'Luxury flat with wooden interiors'),
       (1, 4, 'FLAT', 76, 'Charming flat for couples'),
       (3, 10, 'APARTMENT', 170, 'Premium apartment with 3 bedrooms'),
       (4, 1, 'HOME', 225, 'Home with private vineyard'),
       (2, 6, 'FLAT', 98, 'Flat with balcony and great views'),
       (1, 3, 'FLAT', 72, 'Cozy and quiet flat'),
       (3, 8, 'APARTMENT', 140, 'Apartment with open kitchen concept'),
       (4, 7, 'HOME', 235, 'Luxury home with smart home features'),
       (2, 2, 'FLAT', 90, 'Flat near business district'),
       (1, 10, 'FLAT', 80, 'Top-floor flat with sunlight'),
       (3, 5, 'APARTMENT', 160, 'Family-friendly apartment with kids play area'),
       (2, 1, 'FLAT', 92, 'Modern flat near city park'),
       (3, 7, 'APARTMENT', 175, 'Luxury apartment with great view'),
       (4, 4, 'HOME', 260, 'Spacious home with beautiful garden'),
       (1, 2, 'FLAT', 85, 'Comfortable flat near historic district'),
       (2, 5, 'FLAT', 110, 'Quiet flat with garden view'),
       (3, 9, 'APARTMENT', 145, 'Apartment with central location'),
       (4, 8, 'HOME', 275, 'Exclusive home with private cinema'),
       (1, 9, 'FLAT', 90, 'Flat with a cozy fireplace'),
       (2, 4, 'HOME', 210, 'Home with scenic countryside view'),
       (3, 6, 'APARTMENT', 155, 'Apartment with rooftop garden'),
       (4, 2, 'HOME', 280, 'Luxury home with marble interiors'),
       (1, 7, 'FLAT', 78, 'Minimalist flat with sleek furniture'),
       (2, 8, 'APARTMENT', 135, 'Apartment near art district'),
       (3, 5, 'FLAT', 102, 'Flat with smart lighting system'),
       (4, 10, 'HOME', 290, 'Exclusive home with grand entrance'),
       (2, 3, 'FLAT', 95, 'Flat with modern kitchen setup'),
       (1, 1, 'FLAT', 70, 'Small but functional flat'),
       (3, 2, 'APARTMENT', 128, 'Apartment with private workspace'),
       (4, 6, 'HOME', 265, 'Spacious home with two-car garage'),
       (2, 9, 'FLAT', 118, 'Flat near shopping mall'),
       (3, 3, 'APARTMENT', 132, 'Apartment with high-speed internet'),
       (4, 9, 'HOME', 270, 'Home with eco-friendly design'),
       (2, 10, 'FLAT', 112, 'Flat with modern furnishing'),
       (1, 5, 'FLAT', 74, 'Flat with rooftop terrace'),
       (3, 1, 'APARTMENT', 138, 'Apartment near financial district'),
       (4, 7, 'HOME', 295, 'Elegant home with classic architecture'),
       (2, 6, 'FLAT', 105, 'Flat with a contemporary design'),
       (1, 8, 'FLAT', 88, 'Compact flat with cozy interiors'),
       (3, 4, 'APARTMENT', 140, 'Apartment with high ceilings'),
       (4, 3, 'HOME', 285, 'Luxury home with vineyard views'),
       (2, 5, 'FLAT', 120, 'Flat with a spacious kitchen'),
       (1, 2, 'FLAT', 79, 'Flat ideal for students'),
       (3, 9, 'APARTMENT', 150, 'Apartment with a modern touch'),
       (4, 1, 'HOME', 300, 'Exclusive mansion with large garden');
